# code: language=ansible
---
- name: Wait for cluster creation completion
  ansible.builtin.wait_for:
    timeout: 300
    sleep: 5
    state: started
    port: "{{ master_kube_api_port }}"
    host: "{{ master_ip }}"

- name: Check if node is already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: worker_kubelet_con

- name: Run kubeadm join
  ansible.builtin.command:
    cmd: "kubeadm join {{ master_ip }}:{{ master_kube_api_port }} --token {{ lookup('env', 'BOOTSTRAP_TOKEN') }} --discovery-token-unsafe-skip-ca-verification"
  when: not worker_kubelet_con.stat.exists
  register: worker_join_result
  changed_when: "'Cluster join command executed' in worker_join_result.stdout"
