# code: language=ansible
---
- name: Create a xfs filesystem on scsi2
  community.general.filesystem:
    fstype: xfs
    dev: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2

- name: Create a directory
  ansible.builtin.file:
    path: /longhorn
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Mount up device by UUID
  ansible.posix.mount:
    path: /longhorn
    src: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2
    fstype: xfs
    opts: defaults
    state: mounted
