# code: language=ansible
---
- name: Create a xfs filesystem on scsi1
  community.general.filesystem:
    fstype: xfs
    dev: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1

- name: Create a directory
  ansible.builtin.file:
    path: /containerd
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Mount up device by UUID
  ansible.posix.mount:
    path: /containerd
    src: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
    fstype: xfs
    opts: defaults
    state: mounted

- name: Uninstall packages that may interfere with containerd
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
    update_cache: true
  loop:
    - podman
    - buildah

- name: Install yum-utils
  ansible.builtin.dnf:
    name: yum-utils
    state: present
    update_cache: true

- name: Download the YUM repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: Install containerd
  ansible.builtin.dnf:
    name: containerd.io
    state: present
    update_cache: true

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy containerd config file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/config.toml"
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0644"

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
