# code: language=ansible
---
- name: Add exclude to yum.conf
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    regexp: "^exclude="
    line: "exclude=kubelet kubeadm kubectl"
    state: present
    insertafter: EOF

- name: Copy kubernetes repo file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/kubernetes.repo.j2"
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: "0644"

- name: Install kubelet, kubeadm, and kubectl
  ansible.builtin.dnf:
    name: "{{ item.name }}={{ item.version }}"
    state: present
    update_cache: true
    disable_excludes: all
  loop: "{{ kubernetes_packages }}"
