# code: language=ansible
---
- name: Install helm
  ansible.builtin.import_tasks: helm.yml

- name: Import cluster creation tasks
  ansible.builtin.import_tasks: cluster_creation.yml

- name: Install Cilium
  ansible.builtin.import_tasks: cilium.yml
