# code: language=yaml
---
kernel_modules:
  - overlay
  - br_netfilter
sysctl_params:
  - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
  - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
  - { name: "net.ipv4.ip_forward", value: "1" }
kubernetes_repo_version: "1.35"
kubernetes_packages:
  - { name: "kubelet", version: "1.35.4" }
  - { name: "kubeadm", version: "1.35.4" }
  - { name: "kubectl", version: "1.35.4" }
  